from __future__ import annotations
import base64,json,os,re,shutil,subprocess,tempfile,urllib.error,urllib.request
from fastapi import FastAPI,HTTPException,Header
from pydantic import BaseModel,Field
app=FastAPI(title="Mismar Coding Worker")
class BuildRequest(BaseModel):
    task:str=Field(min_length=1,max_length=12000); repo:str|None=None; base:str|None=None; branch:str|None=None; builder:str|None=None
def github_api(path,token,method="GET",body=None):
    data=json.dumps(body).encode() if body is not None else None
    req=urllib.request.Request("https://api.github.com"+path,data=data,method=method,headers={"Authorization":f"Bearer {token}","Accept":"application/vnd.github+json","Content-Type":"application/json","X-GitHub-Api-Version":"2022-11-28"})
    try:
        with urllib.request.urlopen(req,timeout=20) as r:return json.loads(r.read().decode())
    except urllib.error.HTTPError as exc: raise RuntimeError(f"GitHub API {exc.code}: {exc.read().decode('utf-8','replace')[:500]}") from exc
def run(cmd,cwd,env):
    p=subprocess.run(cmd,cwd=cwd,env=env,text=True,capture_output=True,timeout=1800,check=False)
    if p.returncode: raise RuntimeError((p.stdout+"\n"+p.stderr)[-4000:])
    return p.stdout[-4000:]
def safe_branch(task):
    slug=re.sub(r"[^a-zA-Z0-9-]+","-",task.lower()).strip("-")[:45] or "ai-task"; return f"ai/{slug}-{os.urandom(3).hex()}"
def clone(repo,base,token,path):
    encoded=base64.b64encode(f"x-access-token:{token}".encode()).decode(); env=os.environ.copy()
    env.update({"GIT_CONFIG_COUNT":"1","GIT_CONFIG_KEY_0":"http.https://github.com/.extraheader","GIT_CONFIG_VALUE_0":f"AUTHORIZATION: basic {encoded}","GIT_TERMINAL_PROMPT":"0"})
    run(["git","clone","--depth","1","--branch",base,f"https://github.com/{repo}.git",path],"/tmp",env); return env
@app.get("/health")
def health():return {"ok":True,"service":"mismar-coding-worker","github":bool(os.getenv("GITHUB_TOKEN"))}
@app.post("/build")
def build(req:BuildRequest, authorization: str | None = Header(default=None)):
    secret=os.getenv("MISMAR_WORKER_SHARED_SECRET","").strip()
    if not secret or authorization != "Bearer "+secret: raise HTTPException(401,"Unauthorized")
    token=os.getenv("GITHUB_TOKEN"); repo=req.repo or os.getenv("GITHUB_REPO")
    if not token or not repo: raise HTTPException(503,"Worker يحتاج GITHUB_TOKEN و GITHUB_REPO")
    base=req.base or os.getenv("MISMAR_WORK_BASE","main"); branch=req.branch or safe_branch(req.task); root=tempfile.mkdtemp(prefix="mismar-worker-")
    try:
        env=clone(repo,base,token,root); run(["git","checkout","-b",branch],root,env)
        from builders.registry import select_builder
        builder=select_builder(req.builder)
        if not builder: raise RuntimeError("لا يوجد coding builder متوفر في Worker")
        from builders.base import BuildRequest as BuilderRequest
        result=builder.run(BuilderRequest(task=req.task,repo_path=root,branch=branch,max_attempts=2))
        if not result.ok: raise RuntimeError(result.logs[-3500:] or result.summary)
        status=run(["git","status","--short"],root,env)
        if not status.strip(): return {"ok":True,"branch":branch,"changed_files":[],"message":"المبرمج لم ينتج تغييرات."}
        run(["git","add","-A"],root,env)
        run(["git","-c","user.name=Mismar AI","-c","user.email=mismar-ai@users.noreply.github.com","commit","-m","feat: implement AI company task"],root,env)
        run(["git","push","origin",branch],root,env)
        pr=github_api(f"/repos/{repo}/pulls",token,"POST",{"title":"feat: AI employee implementation","head":branch,"base":req.base,"body":"Generated by Mismar Coding Worker. CI must pass and a human must approve before merge."})
        return {"ok":True,"branch":branch,"pr_url":pr.get("html_url"),"pr_number":pr.get("number"),"changed_files":result.changed_files,"summary":result.summary}
    finally: shutil.rmtree(root,ignore_errors=True)
